apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      database: postgresql
  template:
    metadata:
      labels:
        database: postgresql
    spec:
      containers:
        - name: postgresql-container
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: root
            - name: POSTGRESQL_USERNAME
              value: postgres      
            - name: POSTGRESQL_DATABASE
              value: YarismaProjesiDB
            - name: POSTGRESQL_PGHBA_REMOVE_FILTERS
              value: local, md5