apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-config
  labels:
    team: competitiondevs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service   

  template:
    metadata:
      name: config-service
      labels:
        app: config-service

      annotations:
        olusturan: Can Demirhan
        email: c@demir.com

    spec:
      containers:        
        - image: ysfyrdmcl/questiongame:v001
          name:  podconfig
          resources:
            requests: 
              memory: "1Gi"
              cpu: "0.1"
            limits:
              memory: "2Gi"
              cpu: "0.25"
          ports:
            - containerPort: 8888