apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-user
  labels:
    team: competitiondevs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service   

  template:
    metadata:
      name: user-service
      labels:
        app: user-service

      annotations:
        olusturan: Can Demirhan
        email: c@demir.com

    spec:
      containers:        
        - image: ysfyrdmcl/questiongameuser:v002
          name:  poduser
          resources:
            requests: 
              memory: "1Gi"
              cpu: "0.1"
            limits:
              memory: "2Gi"
              cpu: "0.25"
          ports:
            - containerPort: 9091 
          env:
            - name: SERVERPORT
              valueFrom:
                secretKeyRef: 
                  name: secret-competition
                  key: auth_port
            - name: DBUSERNAME
              valueFrom: 
                secretKeyRef:
                  name: secret-competition
                  key: db_username
            - name: DBPASSWORD
              valueFrom:
                secretKeyRef: 
                  name: secret-competition
                  key: db_password
            - name: DBURL
              valueFrom:
                secretKeyRef: 
                  name: secret-competition
                  key: db_url
            - name: AUTHURL
              valueFrom:
                secretKeyRef: 
                  name: secret-competition
                  key: auth_url
            - name: USERURL
              valueFrom:
                secretKeyRef: 
                  name: secret-competition
                  key: user_url
            - name: MAINURL
              valueFrom:
                secretKeyRef: 
                  name: secret-competition
                  key: main_url
            - name: CONFIGSERVER
              valueFrom:
                secretKeyRef:
                  name: secret-competition
                  key: config_server_url